# .github/workflows/update-rules.yml

name: Update AdGuard Rules

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to process rules and update README
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        # ✨ 修改：运行位于 documents 文件夹内的脚本
        run: python documents/process_rules.py

      - name: Commit and push if changes
        run: \vert{}
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 检查是否有文件变动
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi
          
          # 添加所有可能变动的文件
          git add Black.txt White.txt README.md
          
          BLOCK_COUNT=$(grep -v -c '^!' Black.txt \vert{}\vert{} echo 0)
          WHITE_COUNT=$(grep -v -c '^!' White.txt || echo 0)
          git commit -m "chore: 自动更新规则列表
          
          - 黑名单规则: ${BLOCK_COUNT} 条
          - 白名单规则: ${WHITE_COUNT} 条"
          
          git push
